### ISSUE TITLE
Certificados (Contrato Retirado)

### ISSUE THREAD

**Issue by krodriguez93** [Shinseiki86/sgh#3]
Cuando se intenta generar un certificado de un contrato retirado se despliega un error en la generación.

**Comment by Shinseiki86** [comment]
Se realizan pruebas, pero no se detecta error. Por favor adjuntar pantallazo.

![865f0bc5-e5c7-4b3b-9933-35c074434358](https://user-images.githubusercontent.com/22685115/34996297-31228064-faa7-11e7-9fd0-ab41afc39d53.jpg)

**Comment by krodriguez93** [comment]
Hola, ya revise y se debe a que no están creadas todas las carpetas del empleador, es decir las que contienen las imágenes necesarias para la construcción del PDF.

se puede finalizar el ISSUE.
________________________________
De: Diego Cortés <notifications@github.com>
Enviado: martes, 16 de enero de 2018 7:23 a. m.
Para: Shinseiki86/sgh
Cc: krodriguez93; Author
Asunto: Re: [Shinseiki86/sgh] Certificados (Contrato Retirado) (#3)


Se realizan pruebas, pero no se detecta error. Por favor adjuntar pantallazo.

[865f0bc5-e5c7-4b3b-9933-35c074434358]<https://user-images.githubusercontent.com/22685115/34996297-31228064-faa7-11e7-9fd0-ab41afc39d53.jpg>

[https://user-images.githubusercontent.com/22685115/34996297-31228064-faa7-11e7-9fd0-ab41afc39d53.jpg]
